config/routes.rb
Rails.application.routes.draw do
 

  
scope "(:locale)", locale: /en|fr/ do
  
  
  resources :plans 
       
  resources :subscriptions
   

  resources :interiordesigners do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :countertops do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :customcabinets do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :cashbuyers do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :movingcompanies do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :poolrepairs do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :poolcleaners do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :solarscreens do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :windows do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :termiteinspectors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :taxspecialists do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :titlecompanies do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :septics do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :securities do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :stagings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :rentalproperties do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :accountants do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :lawyers do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :real_estatefirms do 
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :realtors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :roofings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :privatebanks do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :privatefirms do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :propertymanagementfirms do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :paintings do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :plumbings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :molds do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :mortgages do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :landsurveyors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :landscapings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :insulations do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :hardmoneys do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :homeinspectors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :generalcontractors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :floorings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :framings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :drywalls do
      collection do
      get 'search'
      get :autocomplete
    end
  end
  resources :orders
  
  devise_for :users
  resources :subscriptionpackages do
    resources :orders
  end
  resources :asphalts do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :airconditioners do
    collection do
      get 'search'
    get :autocomplete
    end
  end  

  resources :services do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :arquitects do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  

  

 
  resources :commercialpropertiesforsales do
    collection do
      get 'search'
    end
  end
  
  resources :service_types

  resources :residentials do
    collection do
      get 'search'
      get 'bedrooms'
      get :autocomplete
    end
  end

  get 'pages/home'
  get 'pages/car'
  get 'pages/dealer'
  get 'pages/useddealer'
  get 'pages/semitrailer'
  get 'pages/semitruck'
  get 'pages/truckdealer'
  get 'pages/usedsemitruckdealer'
  get 'pages/semitruckservices'
  get 'pages/semitrailerservices'
  get 'pages/semitrailerdealer'
  get 'pages/usedsemitrailerdealer'
  get 'pages/membership'
  get 'pages/termsofuse'
  get 'pages/privacypolicy'
  get 'pages/heavyequipment'
  get 'pages/heavyequipmentservices'
  get 'pages/heavydealer'
  get 'pages/usedheavydealer'
  get 'pages/farm'
  get 'pages/farmdealer'
  get 'pages/farmequipmentservices'
  get 'pages/usedfarmdealer'
  get 'pages/contactus'
  get 'pages/carservices'
  get 'seller' => "subscriptionpackages#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'pages#home'
  
end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "default.jpg",
			
	:storage => :dropbox,
      :dropbox_credentials => Rails.root.join("config/dropbox.yml")
      validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
      
	belongs_to :plan
	validates_presence_of :email
	

	attr_accessor :stripe_card_token

	def save_with_payment
		if valid?
			customer = Stripe::Customer.create(description: email, email: email, plan: name, card: stripe_card_token)
			self.stripe_customer_token = customer.id
			save!
		end
	 # Handle exceptions
   rescue Stripe::APIError => e
      logger.error "Stripe Authentication error while creating user: #{e.message}"
      errors.add :base, "Our system is temporarily unable to process credit cards."
      false
	end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:destroy]

  def index
    @subscriptions = Subscription.all
  end

  def show
  end

  def new
    @subscription = Subscription.new
  end

  def edit
  end

  def create
    @subscription = Subscription.new(subscription_params)
    #@plan = Plan.find(params[:name])
    #@subscription.name = @plan.name
    if @subscription.save_with_payment
      redirect_to  @subscription, :notice => "Thank you for subscribing!"
    else
      render :new
    end
  end

  def update
    @subscription.update(subscription_params)
  end

  def destroy
    @subscription.destroy
  end

  private
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def subscription_params
      params.require(:subscription).permit(:email, :name, :description, :stripe_card_token, :company_name, :website, :address, :zipcode, :city, :phone, :contact, :company_email, :card_name, :bill_address, :image)
    end
    def check_user
        unless current_user.admin?
         redirect_to root_url, alert: "Sorry, Only Ontario's Only Admin can Delete a Subscription"
    end
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription,:html => { :multipart => true }) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>

     
    <br>
    <div class="thumbnail">
      <div class="field">
    <%= label_tag :nil, "COMPANY INFORMATION FOR ADVERTISE IN OUR WEBSITE" %>
    </div>
    <div class="form-group">
    <div class="row">
      <div class="col-md-4">
        <%= label_tag :business_name %><br>
        <%= f.text_field :company_name, class: "form-control" %>
        </div>
        <div class="col-md-4">
        <%= label_tag :website %><br>
        <%= f.text_field :website, class: "form-control" %><br>
        </div>
        <div class="col-md-4">
        <%= label_tag :address %><br>
        <%= f.text_area :address, class: "form-control" %><br>
        </div>
        <div class="col-md-4">
        <%= label_tag :zip_code %><br>
       <%= f.text_field :zipcode, class: "form-control" %>
        </div>
        <div class="col-md-4">
        <%= label_tag :city %><br>
        <%= f.text_field :city, class: "form-control" %>
        </div>
        <div class="col-md-4">
        <%= label_tag :business_phone %><br>
        <%= f.text_field :phone, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
    <div class="row">
        <div class="col-md-4">
        <%= label_tag :contact_name %><br>
        <%= f.text_field :contact, class: "form-control" %>
        </div>
        <div class="col-md-4">
        <%= label_tag :business_email %><br>
        <%= f.text_field :company_email, class: "form-control" %>
        </div>
        <div class="col-md-4">
        <%= f.label :pictures %>  <%= f.file_field :image, class: "form-control" %><br><br>
        </div>
        <br>
        <br>
    </div>
  </div>
  </div>
    <br>
    

    <%= f.label :name, "PLEASE SELECT THE TYPE OF PLAN YOU WANT TO SUBSCRIBE" %><br>
    <%= f.select :name, options_for_select([["Basic Advertising Plan $49.99","Basic"],["Gold Advertising Plan $99.99", "Gold"]]), class: "form-control" %>
  <br>
  <br>
  <%= f.hidden_field :stripe_card_token %>
  <br>
  <div class="thumbnail">
    <div class="field">
    <%= label_tag :nil, "PAYMENT INFORMATION" %>
    </div>
  <div class="row">
      <div class="col-md-4">
    <%= label_tag :name %><br>
    <%= f.text_field :card_name, class: "form-control" %>
      </div>
    <div class="col-md-8">
    <%= label_tag :billing_address %><br>
    <%= f.text_field :bill_address, class: "form-control"  %>
    </div>
     <div class="col-md-4">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control"  %>
    </div>
  </div>
  <br>
  <% if @subscription.stripe_card_token.present? %>
  Credit card has been provided.
  <% else %>
  <div class="form-group">
    <div class="row">
      
      <div class="col-md-4">
      <%= label_tag :card_number, "Credit Card Number" %>
      <%= text_field_tag :card_number, nil, name: nil, class: "form-control"  %>
      </div>
        <div class="col-md-2">
        <%= image_tag("creditcard.png", :size => "220x33", :alt => "Credit" ) %>      
      </div>
      </div>
    </div>
    <div class="form-group">
    <div class="row">
      <%= image_tag("cardsecurity.png", :size => "40x30", :alt => "Credit" ) %> 
      <div class="col-md-2">
        <%= label_tag :nil, "Security Code(CVV)" %><br>
      <%= text_field_tag :card_code, nil, name: nil, class: "form-control"%>
      </div>
       
      </div>
    </div>
    <div class="form-group">
      <%= label_tag :card_month, "Card Expiration" %>
    <div class="row">
      <div class="col-md-3">
    <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month", class: "form-control"}  %>
  </div>
   <div class="col-md-3">
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year", class: "form-control" } %>
  </div>
</div>
</div>
 <div class="form-group">
  <div class="row">
 <div class="right">
  <div class="col-md-12">
    <%= image_tag("securepayment.png", :size => "140x70", :alt => "Credit" ) %> 
    <%= image_tag("pcicompliant.png", :size => "120x70", :alt => "Credit" ) %> 
  </div>
</div>
  </div>
  </div>
</div>
<% end %>
    <div class="actions">
    <%= f.submit "Submit my Order", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th>Company Logo</th>
    <th>Company Name</th>
    <th>Company Website</th>
    <th>Address</th>
    <th>City</th>
    <th>Zipcode</th>
    <th>Phone</th>
    <th>Action</th>
  </tr>

  <% @subscriptions.each do |subscription| %>
    <tr>
     <td><%= image_tag subscription.image.url(:medium) %></td>
      <strong><td><%= subscription.company_name %></td></strong>
      <td><%= link_to subscription.website, subscription.website %></td>
      <td><%= subscription.address %></td>
      <td><%= subscription.city %></td>
      <td><%= subscription.zipcode %></td>
      <td><%= subscription.phone %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", subscription, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_subscription_path(subscription), class: "btn btn-link" %></li>
            <% if user_signed_in? && current_user.admin? %>
            <li><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
            <% end %>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<br>
   

<br>
<br>

<div class="left">

<%= link_to 'Subscribe', new_subscription_path, class: "btn btn-success" %>
</div>

<br>


<br>

app/views/subscriptions/new.html.erb
<div class="jumbotron">
 	<div class="left">
 	<h2>Advertise a Motors Service</h2>	
 </div>
 </div>
<br>
<%= render 'form' %>
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= image_tag @subscription.image.url %>
      <strong><%= @subscription.company_name %></strong>
      <br>
      <br>
      <strong>Company website:</strong>
      <%= link_to @subscription.website, @subscription.website %><br>
      <strong>Company phone:</strong>
     <%= @subscription.phone %><br>
     <strong>Address:</strong>
     <%= @subscription.address %><br>
      <strong>City:</strong> 
     <%= @subscription.city %><br>
     <strong>Zipcode:</strong>
     <%= @subscription.zipcode %><br>
    </div>
     <br>

  </div>
  <div class="col-md-6">
<iframe
  width="500"
  height="180"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAUOQ0h7ZYU56FuY9ziMMXURoIlHxC3pfY
    &q=<%= @subscription.address.parameterize %>">
</iframe>
  </div>

</div>


<%= link_to 'Edit', edit_subscription_path(@subscription), class: "btn btn-link" %> |
<%= link_to 'Back', subscriptions_path, class: "btn btn-link" %>