config/routes.rb
Rails.application.routes.draw do
 

  
scope "(:locale)", locale: /en|fr/ do
  
  
  resources :plans 
       
  resources :subscriptions
   

  resources :interiordesigners do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :countertops do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :customcabinets do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :cashbuyers do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :movingcompanies do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :poolrepairs do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :poolcleaners do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :solarscreens do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :windows do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :termiteinspectors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :taxspecialists do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :titlecompanies do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :septics do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :securities do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :stagings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :rentalproperties do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :accountants do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :lawyers do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :real_estatefirms do 
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :realtors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :roofings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :privatebanks do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :privatefirms do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :propertymanagementfirms do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :paintings do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :plumbings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :molds do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :mortgages do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :landsurveyors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :landscapings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :insulations do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :hardmoneys do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :homeinspectors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :generalcontractors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :floorings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :framings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :drywalls do
      collection do
      get 'search'
      get :autocomplete
    end
  end
  resources :orders
  
  devise_for :users
  resources :subscriptionpackages do
    resources :orders
  end
  resources :asphalts do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :airconditioners do
    collection do
      get 'search'
    get :autocomplete
    end
  end  

  resources :services do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :arquitects do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  

  

 
  resources :commercialpropertiesforsales do
    collection do
      get 'search'
    end
  end
  
  resources :service_types

  resources :residentials do
    collection do
      get 'search'
      get 'bedrooms'
      get :autocomplete
    end
  end

  get 'pages/home'
  get 'pages/car'
  get 'pages/dealer'
  get 'pages/useddealer'
  get 'pages/semitrailer'
  get 'pages/semitruck'
  get 'pages/truckdealer'
  get 'pages/usedsemitruckdealer'
  get 'pages/semitruckservices'
  get 'pages/semitrailerservices'
  get 'pages/semitrailerdealer'
  get 'pages/usedsemitrailerdealer'
  get 'pages/membership'
  get 'pages/termsofuse'
  get 'pages/privacypolicy'
  get 'pages/heavyequipment'
  get 'pages/heavyequipmentservices'
  get 'pages/heavydealer'
  get 'pages/usedheavydealer'
  get 'pages/farm'
  get 'pages/farmdealer'
  get 'pages/farmequipmentservices'
  get 'pages/usedfarmdealer'
  get 'pages/contactus'
  get 'pages/carservices'
  get 'seller' => "subscriptionpackages#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'pages#home'
  
end

end

app/models/privatefirm.rb
class Privatefirm < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "default.jpg",
			
	:storage => :dropbox,
      :dropbox_credentials => Rails.root.join("config/dropbox.yml")
      validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	searchkick autocomplete: ['query']
end

app/controllers/privatefirms_controller.rb
class PrivatefirmsController < ApplicationController
  before_action :set_privatefirm, only: [:show, :edit, :update, :destroy]

  def search
    if params[:search].present?
     @privatefirms = Privatefirm.search(params[:search])
    else
     @privatefirms = Privatefirm.all
    end
  end
  

  def index
    @privatefirms = Privatefirm.all
  end

  def show
  end

  def new
    @privatefirm = Privatefirm.new
  end

  def edit
  end

  def create
    @privatefirm = Privatefirm.new(privatefirm_params)
     @privatefirm.user_id = current_user.id
    respond_to do |format|
      if @privatefirm.save
        format.html { redirect_to @privatefirm, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @privatefirm }
      else
        format.html { render :new }
        format.json { render json: @privatefirm.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if   @privatefirm.update(privatefirm_params)
        format.html { redirect_to @privatefirm, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @privatefirm}
      else
        format.html { render :edit }
        format.json { render json: @privatefirm.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
     @privatefirm.destroy
    respond_to do |format|
      format.html { redirect_to privatefirm_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
  end
end

  private
    def set_privatefirm
      @privatefirm = Privatefirm.find(params[:id])
    end

    def privatefirm_params
      params.require(:privatefirm).permit(:company_name, :company_description, :address, :city, :zipcode, :contact_name, :company_website, :company_phone, :image)
    end
    def check_user
      if current_user != @subscriptionpackage.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
  end
end

app/helpers/privatefirms_helper.rb
module PrivatefirmsHelper
end

app/views/privatefirms/_form.html.erb
<%= form_for(@privatefirm) do |f| %>
  <% if @privatefirm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@privatefirm.errors.count, "error") %> prohibited this privatefirm from being saved:</h2>

      <ul>
      <% @privatefirm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :company_description %><br>
    <%= f.text_area :company_description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.number_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br>
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :company_website %><br>
    <%= f.text_field :company_website %>
  </div>
  <div class="field">
    <%= f.label :company_phone %><br>
    <%= f.text_field :company_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/privatefirms/edit.html.erb
<h1>Editing privatefirm</h1>

<%= render 'form' %>

<%= link_to 'Show', @privatefirm %> |
<%= link_to 'Back', privatefirms_path %>

app/views/privatefirms/index.html.erb
<h1>Listing privatefirms</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Company description</th>
      <th>Address</th>
      <th>City</th>
      <th>Zipcode</th>
      <th>Contact name</th>
      <th>Company website</th>
      <th>Company phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @privatefirms.each do |privatefirm| %>
      <tr>
        <td><%= privatefirm.company_name %></td>
        <td><%= privatefirm.company_description %></td>
        <td><%= privatefirm.address %></td>
        <td><%= privatefirm.city %></td>
        <td><%= privatefirm.zipcode %></td>
        <td><%= privatefirm.contact_name %></td>
        <td><%= privatefirm.company_website %></td>
        <td><%= privatefirm.company_phone %></td>
        <td><%= link_to 'Show', privatefirm %></td>
        <td><%= link_to 'Edit', edit_privatefirm_path(privatefirm) %></td>
        <td><%= link_to 'Destroy', privatefirm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Privatefirm', new_privatefirm_path %>

app/views/privatefirms/new.html.erb
<h1>New privatefirm</h1>

<%= render 'form' %>

<%= link_to 'Back', privatefirms_path %>

app/views/privatefirms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @privatefirm.company_name %>
</p>

<p>
  <strong>Company description:</strong>
  <%= @privatefirm.company_description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @privatefirm.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @privatefirm.city %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @privatefirm.zipcode %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @privatefirm.contact_name %>
</p>

<p>
  <strong>Company website:</strong>
  <%= @privatefirm.company_website %>
</p>

<p>
  <strong>Company phone:</strong>
  <%= @privatefirm.company_phone %>
</p>

<%= link_to 'Edit', edit_privatefirm_path(@privatefirm) %> |
<%= link_to 'Back', privatefirms_path %>